finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'squirrels'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('squirrels.urls')),
]

squirrels/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'squirrels'

urlpatterns = [
        path('map/',views.map, name='map'),
        path('', views.sightings),
        path('sightings/', views.sightings, name='view'),
        path('sightings/add/',views.add, name='add'),
        path('sightings/update/', views.update, name='update'),
        path('sightings/stats/', views.stats, name='stats'),
        path('sightings/<int:sighting_id>/', views.detail, name='detail'),
        ]

squirrels/models.py
from django.db import models
from django.utils.translation import gettext as _

class SquirrelDB(models.Model):
    X = models.FloatField(
            max_length = 20,
            help_text = _('Longitude coordinate for squirrel sighting point'),
        )
    Y = models.FloatField(
            max_length = 20,
            help_text = _('Latitude coordinate for squirrel sighting point'),
        )
    sq_id = models.CharField(
            max_length = 100,
            help_text = _('Identification tag for each squirrel sightings'),
        )
    Hect = models.CharField(
            max_length = 20,
            help_text = _('Hectare of Sighting'),
        )
    SHIFT_CHOICES = [
            ('AM', _('AM')),
            ('PM', _('PM')),
        ]
    Shift = models.CharField(
            max_length = 2,
            help_text = _('Shift of Sighting'),
            choices = SHIFT_CHOICES,
            default = 'AM',
        )
    Date = models.DateField(
            help_text = _('Date of Sighting'), 
        )
    Hect_sq_num = models.CharField(
            max_length = 20,
            help_text = _('Number within the chronological sequence of squirrel sightings'),
        )
    Age_choices = [
            ('Adult', _('Adult')),
            ('Juvenile', _('Juvenile'))
        ]
    Age = models.CharField(
            max_length = 10,
            help_text = _('Age of squirrel'),
            choices = Age_choices,
            blank = True,
        )
    Primary_color_choices = [
            ('Gray', _('Gray')),
            ('Black', _('Black')),
            ('Cinnamon', _('Cinnamon')),
        ]
    Primary_color = models.CharField(
            max_length = 10,
            choices = Primary_color_choices,
            blank = True,
            help_text = _('Primary color of squirrel'),
        )
    Highlight_color_choices = [
            ('Gray', _('Gray')),
            ('Black', _('Black')),
            ('Cinnamon', _('Cinnamon')),
        ]
    Highlight_color = models.CharField(
            max_length = 10,
            choices = Highlight_color_choices,
            blank = True,
            help_text = _('Highlight fur color'),
        )
    Combo = models.CharField(
            max_length = 30,
            blank = True,
            help_text = _('Combination of primary and highlight color'),
        )
    Color_notes = models.TextField(
            blank = True,
            help_text = _('Color notes of squirrel'),
        )
    Location_choices = [
            ('Ground Plane', _('Ground Plane')),
            ('Above Ground', _('Above Ground')),
        ]
    Location = models.CharField(
            max_length = 20,
            help_text = _('Location of squirrel'),
            choices = Location_choices,
            blank = True,
        )
    Above_measure = models.CharField(
            max_length = 10,
            blank = True,
            help_text = _('Above ground sighter measurement of squirrel'),
        )
    Specific_loc = models.TextField(
            blank = True,
            help_text = _('Specific location of squirrel'),
        )
    Running = models.BooleanField(
            help_text = _('Squirrel was seen running'),
        )
    Chasing = models.BooleanField(
            help_text = _('Squirrel was seen chasing another squirrel'),
        )
    Climbing = models.BooleanField(
            help_text = _('Squirrel was seen climbing a tree or other environmental landmark'),
        )
    Eating = models.BooleanField(
            help_text = _('Squirrel was seen eating'),
        )
    Foraging = models.BooleanField(
            help_text = _('Squirrel was seen foraging for food'),
        )
    Other_act = models.TextField(
            blank = True,
            help_text = _('Other activities squirrel was doing'),
        )
    Kuks = models.BooleanField(
            help_text = _('Squirrel was heard kukking'),
        )
    Quass = models.BooleanField(
            help_text = _('Squirrel was heard quaaing'),
        )
    Moans = models.BooleanField(
            help_text = _('Squirrel was heard moaning'),
        )
    Tail_flag = models.BooleanField(
            help_text = _('Squirrel was seen flagging its tail'),
        )
    Tail_twitch = models.BooleanField(
            help_text = _('Squirrel was seen twitching its tail'),
        )
    Approaches = models.BooleanField(
            help_text = _('Squirrel was seen approaching human, seeking food'),
        )
    Indifferent = models.BooleanField(
            help_text = _('Squirrel was indifferent to human presence'),
        )
    Runs_from = models.BooleanField(
            help_text = _('Squirrel was seen running from humans, seeing them as a threat'),
        )		
    Other_interactions = models.TextField(
            blank = True,
            help_text = _('Sighter notes on other types of interactions between squirrels and humans'),
        )
    Lat_long = models.CharField(
            max_length = 100,
            help_text = _('Latitude and longitude'),
        )
    def __str__(self):
        return self.sq_id

squirrels/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from datetime import datetime

from django.db.models import Max, Count

from .models import SquirrelDB


def map(request):
    sightings = SquirrelDB.objects.all().filter(Primary_color = 'Black')
    context = {
            'sightings': sightings,
    }
    return render(request, 'squirrels/map.html', context)


def sightings(request):
    sightings = SquirrelDB.objects.all()
    context = {
            'sightings': sightings,
    }
    return render(request,'squirrels/sightings.html', context)


def detail(request, sighting_id):
    # retrieve the selected object's details, and provides an option to update the entries.

    sighting = get_object_or_404(SquirrelDB, pk=sighting_id)


    context = {
            'sighting': sighting,
    }
    return render(request, 'squirrels/detail.html', context)


def update(request):
    # check if it is GET or POST
    if request.method == "POST" and request.POST.get('submit_id') == "Update":
        sighting_id = request.POST.get('sighting_id')
        sighting = get_object_or_404(SquirrelDB, pk=sighting_id)
        sighting.Shift = request.POST.get('Shift_id')
        sighting.X = request.POST.get('long_id')
        sighting.Y = request.POST.get('lat_id')
        sighting.Lat_long = "POINT (%s %s)" % (sighting.Y, sighting.X)
        sighting.Date = datetime.strptime(request.POST.get('Date_id'), "%b. %d, %Y")
        sighting.Age = request.POST.get('Age_id')
        sighting.save()
    context = {
        'sighting': sighting, "status": "Updated"
    }
    return render(request, 'squirrels/confirm.html', context)


def add(request):
    if request.method == "POST" and request.POST.get('submit_id') == "Save":
        if len(request.POST.get('Date_id')) > 0 and "." in request.POST.get('Date_id') \
                and "," in request.POST.get('Date_id') and len(request.POST.get('sighting_sq_id')) > 0\
                and len(request.POST.get('Shift_id')) > 0 and len(request.POST.get('long_id')) > 0 \
                and len(request.POST.get('lat_id')) > 0:
            sighting = SquirrelDB()
            sighting.id = SquirrelDB.objects.aggregate(Max("id"))['id__max']
            sighting.sq_id = request.POST.get('sighting_sq_id')
            sighting.Shift = request.POST.get('Shift_id')
            sighting.X = request.POST.get('long_id')
            sighting.Y = request.POST.get('lat_id')
            sighting.Lat_long = "POINT (%s %s)" % (sighting.Y, sighting.X)
            try:
                # parse the date with given format
                sighting.Date = datetime.strptime(request.POST.get('Date_id'), "%b. %d, %Y")
            except Exception as e:
                # date parsing fails due to absence of space in between
                sighting.Date = datetime.strptime(request.POST.get('Date_id'), "%b.%d, %Y")
            except:
                # Another exception - date parsing fails due to absence of space in between
                sighting.Date = datetime.strptime(request.POST.get('Date_id'), "%b.%d,%Y")
            sighting.Age = request.POST.get('Age_id')
            # set all other options to random values to make sure that the data is saved.
            sighting.Running = True
            sighting.Chasing = True
            sighting.Climbing = True
            sighting.Eating = False
            sighting.Foraging = False
            sighting.Kuks = False
            sighting.Quass = False
            sighting.Moans = False
            sighting.Approaches = False
            sighting.Tail_flag = False
            sighting.Tail_twitch = False
            sighting.Indifferent = False
            sighting.Runs_from = False
            sighting.save()

            # Redirects to confirmation page
            context = {
                'sighting': sighting, "status": "Saved"
            }
        else:
            context = {
                'sighting': "", "status": "Error"
            }
        return render(request, 'squirrels/confirm.html', context)
    else:
        sighting = SquirrelDB()
    context = {
            'sighting': sighting,
    }
    # if it is a new entry request, then page will be redirected to add entry page.
    return render(request, 'squirrels/add.html', context)


def stats(request):
    shift_count = SquirrelDB.objects.all().values('Shift').annotate(total=Count('Shift'))
    date_count = SquirrelDB.objects.all().values('Date').annotate(total=Count('Date'))
    age_count = SquirrelDB.objects.all().values('Age').annotate(total=Count('Age'))
    running = SquirrelDB.objects.all().values('Running').annotate(total=Count('Running'))
    eating = SquirrelDB.objects.all().values('Eating').annotate(total=Count('Eating'))
    context = {
            'shift': shift_count, 'date': date_count, 'age': age_count, 'running': running, 'eating': eating
    }
    return render(request, 'squirrels/stats.html', context)

squirrels/templates/squirrels/add.html
{% extends 'squirrels/base.html' %}
{% load static %}
{% block title %}- Add New Sighting
{% endblock %}
{% block main %}
    <form method="POST">
        {% csrf_token %}
    <table>
     <tr><td>Squirrel ID: </td><td><input type="text" name="sighting_sq_id" size="5"/></td></tr>
     <tr><td>Longitude</td><td><input type="text" name="long_id" size="50"/></td></tr>
        <tr><td>Latitude</td><td><input type="text" name="lat_id" size="50"/></td></tr>
     <tr><td>Shift</td><td><input type="text" name="Shift_id"/></td></tr>
     <tr><td>Date</td><td><input type="text" name="Date_id"/> (Ex: Oct. 21, 2020, Please enter in this format)</td></tr>
     <tr><td>Age</td><td><input type="text" name="Age_id"/></td></tr>
    </table>
    <input type="submit" name="submit_id" value="Save" /> <input type="submit" name="submit_id" value="Cancel" />
        </form>
{% endblock %}
{% block extra_footer %}
{% endblock %}

squirrels/templates/squirrels/base.html
{% load static %}

<!DOCTYPE html>


<!-- saved from url=(0053)https://getbootstrap.com/docs/4.5/examples/dashboard/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Squirrel Sighting {% block title%}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
  <style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style></head>
  <body class="vsc-initialized">
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3"><p class="text-light">Squirrel Sleuths Sarl.</p></a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'squirrels:add' %}">Add a new sighting</a>
      <a class="nav-link" href="{% url 'squirrels:view' %}">List Sightings</a>
        <a class="nav-link" href="{% url 'squirrels:stats' %}">Stats</a>
        <a class="nav-link" href="{% url 'squirrels:map' %}">Map</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
		{% block main %}
		{% endblock %}
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	{% block extra_footer %}
	{% endblock %}


</body></html>

squirrels/templates/squirrels/confirm.html
{% extends 'squirrels/base.html' %}
{% load static %}
{% block title %}
- All Sightings
{% endblock %}
{% block main %}
    <b>
        {% if status != "Error"  %}
            The following data {{ status }} successfully.
            <table>
        <tr><td>Sighting ID: </td><td>{{ sighting.id }}</td></tr>
     <tr><td>Squirrel ID: </td><td>{{ sighting.sq_id }}</td></tr>
     <tr><td>Longitude</td><td>{{sighting.X}}</td></tr>
        <tr><td>Latitude</td><td>{{sighting.Y}}</td></tr>
     <tr><td>Shift</td><td>{{sighting.Shift}}</td></tr>
     <tr><td>Date</td><td>{{sighting.Date}}</td></tr>
     <tr><td>Age</td><td>{{sighting.Age}}</td></tr>
    </table>
        {% else %}
            Error saving the form.
        {% endif %}
    </b>


{% endblock %}
{% block extra_footer %}
{% endblock %}

squirrels/templates/squirrels/detail.html
{% extends 'squirrels/base.html' %}
{% load static %}
{% block title %}
- All Sightings
{% endblock %}
{% block main %}
    <!-- Sends request to update handler, if the user presses Update button -->

    <form method="POST" action="/sightings/update/">
        {% csrf_token %}
    <table>
        <tr><td>Sighting ID: </td><td>{{ sighting.id }}</td></tr>
        <input type="hidden" name="sighting_id" value="{{ sighting.id }}"/>
     <tr><td>Squirrel ID: </td><td>{{ sighting.sq_id }}</td></tr>
     <tr><td>Longitude</td><td><input type="text" name="long_id" size="50" value="{{sighting.X}}"/></td></tr>
        <tr><td>Latitude</td><td><input type="text" name="lat_id" size="50" value="{{sighting.Y}}"/></td></tr>
     <tr><td>Shift</td><td><input type="text" name="Shift_id" value="{{sighting.Shift}}"/></td></tr>
     <tr><td>Date</td><td><input type="text" name="Date_id" value="{{sighting.Date}}"/></td></tr>
     <tr><td>Age</td><td><input type="text" name="Age_id" value="{{sighting.Age}}"/></td></tr>
    </table>
    <input type="submit" name="submit_id" value="Update" /> <input type="submit" name="submit_id" value="Cancel" />
        </form>
    </body>
</html>
{% endblock %}
{% block extra_footer %}
{% endblock %}

squirrels/templates/squirrels/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for sighting in sightings %}
          var point_lat_lon = [{{ sighting.Y }}, {{ sighting.X }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
  </body>
</html>

squirrels/templates/squirrels/sightings.html
{% extends 'squirrels/base.html' %}
{% load static %}
{% block title %}
- All Sightings
{% endblock %}
{% block main %}
	<table>
		<tr>
			<th>Link to Detail Page</th>
			<th>Unique Squirrel ID</th>
			<th>Date</th>
		</tr>
		{% for sighting in sightings %}
		<tr> 
			<td>
			  <li>
		 	    <a href="{% url 'squirrels:detail' sighting.id %}">{{ sighting.id }}</a>
			  </li>
			</td>
			<td>{{ sighting.sq_id }}</td>
			<td>{{ sighting.Date }}</td>
		</tr>
		{% endfor %}
	</table>

{% endblock %}
{% block extra_footer %}
{% endblock %}

squirrels/templates/squirrels/stats.html
{% extends 'squirrels/base.html' %}
{% load static %}
{% block title %}
- All Sightings
{% endblock %}
{% block main %}
<div>

    <div style="margin-left: 10px; position: absolute; top: 50px;">
<table border="1">
    <tr style="background-color: #83f7b2;"><th>Age</th> <th>Count</th></tr>
{% for a in age %}
    <tr><td>{{ a.Age }}</td><td>{{ a.total }} </td>
{% endfor %}
</table>
</div>
    <div style="right: 100px; position: absolute; top: 50px;">
<table border="1">
    <tr style="background-color: #83f7b2;"><th>Shift</th> <th>Count</th></tr>
{% for a in shift %}
    <tr><td>{{ a.Shift }}</td><td>{{ a.total }} </td>
{% endfor %}
</table>
    </div>
    <div style="margin-left: 10px; position: absolute; top: 250px;">
<table border="1">
    <tr style="background-color: #83f7b2;"><th>Running</th> <th>Count</th></tr>
{% for a in running %}
    <tr><td>{{ a.Running }}</td><td>{{ a.total }} </td>
{% endfor %}
</table>
    </div>
    <div style="right: 100px; position: absolute; top: 250px;">
<table border="1">
    <tr style="background-color: #83f7b2;"><th>Eating</th> <th>Count</th></tr>
{% for a in eating %}
    <tr><td>{{ a.Eating }}</td><td>{{ a.total }} </td>
{% endfor %}
</table>
    </div>
    <div style="margin-left: 10px; position: absolute; top: 350px;">
<table border="1">
    <tr style="background-color: #83f7b2;"><th>Date</th> <th>Count</th></tr>
{% for a in date %}
    <tr><td>{{ a.Date }}</td><td>{{ a.total }} </td>
{% endfor %}
</table>
    </div>
</div>
{% endblock %}
{% block extra_footer %}
{% endblock %}